apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node-v0.0.2
spec:
  replicas: 1
  selector:
    app: hello-node
    version: v0.0.2
  template:
    metadata:
      labels:
        app: hello-node
        version: v0.0.2
    spec:
      containers:
      - image: gcr.io/sojern-dev/hello-node:v0.0.2
        name: hello-node
        ports:
        - containerPort: 8081
