apiVersion: v1
kind: ReplicationController
metadata:
    name: hello-node
spec:
    replicas: 1
    selector:
        app: hello-node
        version: "1"
    template:
        metadata:
            labels:
                app: hello-node
                version: "1"
        spec:
            containers:
            - name: hello-node
              image: gcr.io/sojern-dev/hello-node:v1
              ports:
              - containerPort: 8081
