apiVersion: v1
kind: ReplicationController
metadata:
    name: hello-node-v0.0.1
spec:
    replicas: 1
    selector:
        app: hello-node
        version: v0.0.1
    template:
        metadata:
            labels:
                app: hello-node
                version: v0.0.1
        spec:
            containers:
            - name: hello-node
              image: gcr.io/sojern-dev/hello-node:v0.0.1
              ports:
              - containerPort: 8081
