apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node-0.0.2
spec:
  replicas: 1
  selector:
    app: hello-node
    version: 0.0.2
  template:
    metadata:
      labels:
        app: hello-node
        version: 0.0.2
    spec:
      containers:
      - image: gcr.io/sojern-dev/hello-node:0.0.2
        name: hello-node
        ports:
        - containerPort: 8081
