apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
        version: v3.0.0
    spec:
      containers:
      - image: gcr.io/sojern-dev/hello-node:v3.0.0
        name: hello-node
        ports:
        - containerPort: 8081
